<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MICROSOFT-PC" tests="6" failures="1" timestamp="19 Jul 2016 20:14:51 GMT" time="1.036" errors="0">
  <testcase name="testCalculateVacation" time="0.093" classname="TestEmployeeDetails2"/>
  <testcase name="timeTestOne" time="0.502" classname="TestEmployeeDetails2">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.timeTestOne() didn&amp;apos;t finish within the time-out 500">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeTestOne() didn't finish within the time-out 500
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.InterruptedException.<init>(InterruptedException.java:67)
	at java.lang.Thread.sleep(Native Method)
	at TestEmployeeDetails2.timeTestOne(TestEmployeeDetails2.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- timeTestOne -->
  <testcase name="testCalculateDailySalary" time="0.012" classname="TestEmployeeDetails2"/>
  <testcase name="timeTestTwo" time="0.406" classname="TestEmployeeDetails2"/>
  <testcase name="testCalculateTaxAmount" time="0.001" classname="TestEmployeeDetails2"/>
  <testcase name="testCalculateSalaryOnVacation" time="0.008" classname="TestEmployeeDetails2"/>
</testsuite>
